name: Recompile TeaVM
on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            teavm/teavm-maven-webapp/**/*
      - name: Modified files considered echo output
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Recompile for TeaVM
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          bash compile_beta.sh
      - name: Push Local Changes
        if: steps.changed-files.outputs.all_changed_files != ''
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: "Update beta jars"
          branch: ${{ github.head_ref }}
